    CREATE TABLE "order" (
        ID BINARY(255) NOT NULL,
        CUSTOMER_ID VARCHAR(255) NOT NULL,
        PRIMARY KEY (ID)
    );

    CREATE TABLE ORDER_ITEM (
        ID BINARY(255) NOT NULL,
        PRIMARY KEY (ID)
    );