CREATE TABLE AUTHOR (ID BINARY(255) NOT NULL, FIRST_NAME VARCHAR(255), LAST_NAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE BOOK (ID BINARY(255) NOT NULL, ISBN VARCHAR(255), TITLE VARCHAR(255), AUTHOR_ID BINARY(255), PRIMARY KEY (ID));

ALTER TABLE BOOK ADD CONSTRAINT FK_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR;
